### ISSUE TITLE
Full Support for HS200

### ISSUE THREAD

**Issue by pauloruberto** [plasticrake/homebridge-hs100#10]
The current plugin considers the HS200 as an outlet within the Home app, can it be updated so that it will recognize that it is a switch?

**Comment by devbymike** [comment]
You can change it to a switch automatically within the home app under type when you go to edit the device.

**Comment by shivawu** [comment]
So just to make sure, it works, right? Just not recognized correctly, which as pointed out by @devbymike, it can be mixed manually?

**Comment by devbymike** [comment]
Yes, correct.

**Comment by pauloruberto** [comment]
@plasticrake @devbymike, the only options are to choose between an Outlet, Fan, or Light. There is no option for making it appear as a switch. Other plugins such as the ones I use for my WeMo switches appear as switches in the Home app.

**Comment by plasticrake** [comment]
They behave the same, just the icon is different. I can probably make a config option to have HS200 devices show up as as switch. Here's what it looks like to me in iOS 10:

**Service.Switch**

![img_6026](https://user-images.githubusercontent.com/1383980/30282391-08328686-96ca-11e7-8da4-249b4f7bbef4.png)

**Service.Outlet**

![img_6025](https://user-images.githubusercontent.com/1383980/30282392-0833b34e-96ca-11e7-967c-cebf15b6d8d7.png)

**Comment by plasticrake** [comment]
HS200 devices are now added as a Switch by default. There is a config option to add other models as switches as well.
