### ISSUE TITLE
Plugin will crash homebridge if HS100 changes IP

### ISSUE THREAD

**Issue by littlechu** [plasticrake/homebridge-hs100#11]
Try the following

1. Setup HS100 to run.
2. renew the HS100 IP to something else (DHCP sometime do that)
3. Have your IOS device access homekit

you will stuck in the update status until it got not responding.

The following is the homebridge debug log:

Dec 30 21:20:11 raspberrypi homebridge[13017]: HS100 Plug TCP error
Dec 30 21:20:11 raspberrypi homebridge[13017]: Trace: { Error: connect EHOSTUNREACH 192.168.1.119:9999
Dec 30 21:20:11 raspberrypi homebridge[13017]: at Object.exports._errnoException (util.js:1022:11)
Dec 30 21:20:11 raspberrypi homebridge[13017]: at exports._exceptionWithHostPort (util.js:1045:20)
Dec 30 21:20:11 raspberrypi homebridge[13017]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
Dec 30 21:20:11 raspberrypi homebridge[13017]: code: 'EHOSTUNREACH',
Dec 30 21:20:11 raspberrypi homebridge[13017]: errno: 'EHOSTUNREACH',
Dec 30 21:20:11 raspberrypi homebridge[13017]: syscall: 'connect',
Dec 30 21:20:11 raspberrypi homebridge[13017]: address: '192.168.1.119',
Dec 30 21:20:11 raspberrypi homebridge[13017]: port: 9999 }
Dec 30 21:20:11 raspberrypi homebridge[13017]: at Socket.socket.on.on.on (/usr/local/lib/node_modules/homebridge-hs100/node_modules/hs100-api/lib/plug.js:61:17)
Dec 30 21:20:11 raspberrypi homebridge[13017]: at emitOne (events.js:96:13)
Dec 30 21:20:11 raspberrypi homebridge[13017]: at Socket.emit (events.js:188:7)
Dec 30 21:20:11 raspberrypi homebridge[13017]: at emitErrorNT (net.js:1281:8)
Dec 30 21:20:11 raspberrypi homebridge[13017]: at _combinedTickCallback (internal/process/next_tick.js:74:11)
Dec 30 21:20:11 raspberrypi homebridge[13017]: at process._tickCallback (internal/process/next_tick.js:98:9)
Dec 30 21:20:11 raspberrypi homebridge[13017]: [12/30/2016, 9:20:11 PM] { Error: connect EHOSTUNREACH 192.168.1.119:9999
Dec 30 21:20:11 raspberrypi homebridge[13017]: at Object.exports._errnoException (util.js:1022:11)
Dec 30 21:20:11 raspberrypi homebridge[13017]: at exports._exceptionWithHostPort (util.js:1045:20)
Dec 30 21:20:11 raspberrypi homebridge[13017]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
Dec 30 21:20:11 raspberrypi homebridge[13017]: code: 'EHOSTUNREACH',
Dec 30 21:20:11 raspberrypi homebridge[13017]: errno: 'EHOSTUNREACH',
Dec 30 21:20:11 raspberrypi homebridge[13017]: syscall: 'connect',
Dec 30 21:20:11 raspberrypi homebridge[13017]: address: '192.168.1.119',
Dec 30 21:20:11 raspberrypi homebridge[13017]: port: 9999 }

In this case, my HS100 IP changes from 192.168.1.119 to something else.

To resolve this issue, I had to stop homebridge, remove the accessories directory and start home bridge again

I think the issue here is that Homebridge don't know how to handle error and the plugin don't know how to handle cases where device is gone. I suspect you will run into the same issue when you disconnect the device while you try to access homekit

**Comment by pauloruberto** [comment]
I was having this same issue. Found a fix by setting a static ip through my router in order to keep it working.

**Comment by stevens-r** [comment]
@littlechu how do you remove the accessories from directory i gave mine static ips but its still looking for them at the old ip and i dont know witch plug goes with each ip

**Comment by pauloruberto** [comment]
@stevens-r You need to delete the persist and applications folder in ./homebridge, unfortunately it will reset everything through.

**Comment by stevens-r** [comment]
@littlechu Thanks for the help worked great

**Comment by ofonesandzeros** [comment]
If anyone else is encountering this, instead of having to delete accessories and persist and start completely over, I was able to just go into accessories/cachedAccessories and find my outlet in the JSON and update the IP address there (after setting my router to give a persistent DHCP lease to my BE100 mac address).

Make sure you stop homebridge before modifying cachedAccessories though.

**Comment by plasticrake** [comment]
Fixed in 2.0.1 just released. Should now be properly updating to the new IP address when reading from the cache
