### ISSUE TITLE
Plugin continues to load

### ISSUE THREAD

**Issue by jaskegreen** [plasticrake/homebridge-hs100#12]
After starting Homebridge in Terminal, it loads the plugins just fine, then continues loading this every 30 sec:

Online: Dining Room Lamp [8006D4080F8BDBB5FAFCBDCE540D97A717BE08C2]

If I stop the process, Homebridge goes offline. Any thoughts?

**Comment by AlexGustafsson** [comment]
I've had the same problem whenever the plugin can't reach a plug due to TCP errors. It throws the error and then it seems to block all other plugins from reloading. Whenever the connection to the plugin is established again all other plugins load again.

**Comment by plasticrake** [comment]
@jaskegreen Homebridge needs to run continuously in the background. Currently this plugin is a little chatty but either way it will need to be running and messages will appear occasionally.  

@AlexGustafsson The TCP Errors should be reduced in 2.0.1, it is now properly updating IP addresses when the change on startup.

**Comment by kim3er** [comment]
That sounds great. I'll check out the improvements in 2.0.1 (and 2.1.0). Thanks for the update.
