### ISSUE TITLE
State not accurately reported

### ISSUE THREAD

**Issue by EssendonPhoto** [plasticrake/homebridge-hs100#13]
Hi

If the state of a plug is changed outside of Homekit (eg by using the Kasa app or Alexa) then the state of the plug in the Home app changes |(only?) when the room is examined. This is in spite of the plugs being polled every 30 secs for their online status.

Please either stop the regular polling or make it useful by updating the plug on/off status

**Comment by Will711990** [comment]
Hi, same issue !! 
Somebody has a solution ?

thank you !!

**Comment by plasticrake** [comment]
This feature has been added in 2.1.0
