### ISSUE TITLE
error message about duplicate characteristics

### ISSUE THREAD

**Issue by cb2206** [plasticrake/homebridge-hs100#25]
Hi,
I have 3 HS100 Smartplugs and 4 HS200 which were working fine up until homebridge < 0.4.25. Starting with .25 and now with .26, I get an error about trying to add devices with the same UUID. Link to log output: https://www.evernote.com/l/AAHLT2k6xvRMR7v0oGFFMsIf3VyF8FoEkHk

Any advice on trouble shooting this?
Thanks

**Comment by plasticrake** [comment]
What version of homebridge-hs100?

**Comment by cb2206** [comment]
2.2.0 on raspbian jessie

**Comment by plasticrake** [comment]
I can't see your log output. But I know a similar issue was just fixed. #22 But you're on the latest version already. Log output especially with homebrige in debug mode would be helpful.

**Comment by cb2206** [comment]
Here is the screenshot: 
https://www.dropbox.com/s/s73g6g21j1z3let/File%20Aug%2019%2C%2010%2048%2019%20PM.png?dl=0

**Comment by plasticrake** [comment]
Might want to try deleting the .homebridge/accessories and .homebridge/persist folders and try again. Unfortunately this was due to a change in HAP-NodeJS

**Comment by cb2206** [comment]
I already tried and still getting the same error.

**Comment by plasticrake** [comment]
What's the output of: `npm -g list hs100-api`

**Comment by plasticrake** [comment]
Also the output of `npm -g list homebridge`

For me:
homebridge@0.4.26

and `npm -g list hs100-api`
├─┬ homebridge-hs100@2.2.0
│ └── hs100-api@0.7.0

**Comment by plasticrake** [comment]
I'm still unable to reproduce your issue. I deleted my persist and accessory folders and its still working fine. Can you try with only the hs100 plugin in your config? Also a new version of homebridge was released (0.4.27) you may want to try that.

**Comment by cb2206** [comment]
0.4.27 didn't make a difference. I ended up completely deleting everything (all plugins, home bridge, npm, nodejs) and then reinstalling and suddenly it started working again with the same config.json as before. no idea what had happened.
Thanks for taking the time to help me!
