### ISSUE TITLE
TypeError: Cannot read property 'on_off' of undefined

### ISSUE THREAD

**Issue by shidevil** [plasticrake/homebridge-hs100#29]
Updated from 2.2.0 to 3.3.1

Homebridge on latest version. I have a LB130 bulb as well and using the https://github.com/leematt/homebridge-tplink-lightbulb.

my config have already place the deviceTypes. However it still does not work. 

 {
        "platform": "Hs100",
        "name": "TPLink",
        "deviceTypes": ["plug"]
}

Sep 14 23:22:51 raspberrypi homebridge[13914]: /home/pi/homebridge-hs100/node_modules/hs100-api/lib/bulb.js:40
Sep 14 23:22:51 raspberrypi homebridge[13914]: let powerOn = (this.lightState.on_off === 1);
Sep 14 23:22:51 raspberrypi homebridge[13914]: ^
Sep 14 23:22:51 raspberrypi homebridge[13914]: TypeError: Cannot read property 'on_off' of undefined
Sep 14 23:22:51 raspberrypi homebridge[13914]: at Bulb.emitEvents (/home/pi/homebridge-hs100/node_modules/hs100-api/lib/bulb.js:40:35)
Sep 14 23:22:51 raspberrypi homebridge[13914]: at Bulb.set sysInfo (/home/pi/homebridge-hs100/node_modules/hs100-api/lib/device.js:59:10)
Sep 14 23:22:51 raspberrypi homebridge[13914]: at Bulb.set sysInfo [as sysInfo] (/home/pi/homebridge-hs100/node_modules/hs100-api/lib/bulb.js:21:19)
Sep 14 23:22:51 raspberrypi homebridge[13914]: at new Bulb (/home/pi/homebridge-hs100/node_modules/hs100-api/lib/bulb.js:12:41)
Sep 14 23:22:51 raspberrypi homebridge[13914]: at Client.getBulb (/home/pi/homebridge-hs100/node_modules/hs100-api/lib/client.js:123:12)
Sep 14 23:22:51 raspberrypi homebridge[13914]: at Client.getDeviceFromSysInfo (/home/pi/homebridge-hs100/node_modules/hs100-api/lib/client.js:138:41)
Sep 14 23:22:51 raspberrypi homebridge[13914]: at Socket.socket.on (/home/pi/homebridge-hs100/node_modules/hs100-api/lib/client.js:202:29)
Sep 14 23:22:51 raspberrypi homebridge[13914]: at emitTwo (events.js:106:13)
Sep 14 23:22:51 raspberrypi homebridge[13914]: at Socket.emit (events.js:194:7)
Sep 14 23:22:51 raspberrypi homebridge[13914]: at UDP.onMessage (dgram.js:544:8)
Sep 14 23:22:51 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Sep 14 23:22:51 raspberrypi systemd[1]: Unit homebridge.service entered failed state.

**Comment by plasticrake** [comment]
Yeah it should be excluding the Bulb. Can you run homebridge in debug and post the output? `homebridge -D`

**Comment by shidevil** [comment]
@plasticrake

Sure do. I will post the output tomorrow as it's late over here.

**Comment by plasticrake** [comment]
Didn't hear back so I closed this issue. Please reopen if you need help. I've also added bulb support to this project and would love to get your feedback on that! If you want to try bulb support add to your config:
```json
"deviceTypes": ["plug","bulb"]
