### ISSUE TITLE
Error at version 2.1.0

### ISSUE THREAD

**Issue by DutchDeffy** [plasticrake/homebridge-hs100#31]
I have homebrige hs100 version 2.1.0 . But when I run home bridge at debug I get the next error: https://pastebin.com/U48GMdRa . Everything worked fine until last week. Should I upgrade or should I stay?

**Comment by DutchDeffy** [comment]
Also get the an error when I run it using updated version 
log: https://pastebin.com/BNA03pFQ 
config: https://pastebin.com/3xsDRx6A

**Comment by plasticrake** [comment]
What's your node version? `node --version` You didn't specify your node version but it looks to be older that version 6.4 which is required for this to work.

**Comment by DutchDeffy** [comment]
How can I Use 6.4.0 for Homebridge-hs100 plugin while homebridge it delf uses 4.3.2 on Raspberry pi Model B. Is there some way or is another solution needed?

**Comment by plasticrake** [comment]
homebridge uses whatever node version you have installed. You can upgrade it. I'm running version 8 on my Pi.
