### ISSUE TITLE
New Plugin throwing exception on init

### ISSUE THREAD

**Issue by jkowall** [plasticrake/homebridge-hs100#36]
Hello, I am seeing the following error in my configuration:

/usr/local/lib/node_modules/homebridge-hs100/node_modules/hs100-api/lib/client.js:66
      if (this.deviceTypes && !this.deviceTypes.includes(deviceType)) {
                                                ^

TypeError: this.deviceTypes.includes is not a function
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-hs100/node_modules/hs100-api/lib/client.js:66:49)
    at emitTwo (events.js:87:13)
    at Socket.emit (events.js:172:7)
    at UDP.onMessage (dgram.js:506:8)

Have tried to delete persist/ dir, and add a Name : (which wasn't required in the previous iteration).

Thanks!

**Comment by plasticrake** [comment]
What version of node are you running?

**Comment by jkowall** [comment]
4.7.2

**Comment by plasticrake** [comment]
Node v6 is required. You should have seen a warning on startup in the log.

**Comment by jkowall** [comment]
Thanks sir, I didn't see that one. When I set it up there were issues with homebridge on Node6, but I'll do that upgrade now.
