### ISSUE TITLE
power usage widget

### ISSUE THREAD

**Issue by rossi2000** [plasticrake/homebridge-hs100#5]
Hi

been using this plugin for a little while, works perfect!
this is not so much an issue, but an enhancement request.

I use an HS110, would it be possible to add a widget that displays the current power usage?  this plug has these extra features.

**Comment by chris1705** [comment]
Hi,

as far as I see, it's not possible to display the current power usage as widget within Apples Home App. It would be possible to use the current Power Characteristic used by Elgato Eve Energy, but it would be only visible in their app.

See also:  https://gist.github.com/gomfunkel/b1a046d729757120907c

Regards
Chris

**Comment by rossi2000** [comment]
no problem, thanks for the reply.
