### ISSUE TITLE
Auto discovery

### ISSUE THREAD

**Issue by rdollet** [plasticrake/homebridge-hs100#7]
Hi,

I've installed the v2.0 and used the simple config:
 "platforms": [{
        "platform": "Hs100"
    }]
hoping that my hs-100 will be discovered, but nothing is happening.
Kasa works fine btw.

Is there anything special to activate auto-discovery?
Thanks for your help,

Richard

**Comment by plasticrake** [comment]
What is the output of homebridge when starting up? Do you have other platforms or devices and are they working? Another thing to try is deleting the .homebridge/accessories and .homebridge/persist folders and removing and re-adding homebridge to your Home.

**Comment by psqv** [comment]
Having the same problem here. Tried deleting the persist etc and re-add the home bridge to HomeKit, but I can´t find the hs100. Here´s my output log starting up: 

```
[2016-12-18 13:43:28] Loaded plugin: homebridge-hs100
[2016-12-18 13:43:28] Registering platform 'homebridge-hs100.Hs100'
[2016-12-18 13:43:28] ---
[2016-12-18 13:43:28] Loaded config.json with 0 accessories and 1 platforms.
[2016-12-18 13:43:28] ---
[2016-12-18 13:43:28] Loading 1 platforms...
[2016-12-18 13:43:28] Initializing Hs100 platform...
[2016-12-18 13:43:28] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[2016-12-18 13:43:28] Homebridge is running on port 51826.
```

Auto discovery means that i should be able to add the accessory through HomeKit on my iOS device at this point I guess? I´m not getting anything when I try to do that.

Is there some manual setup step in the config.json I´m missing?

**Comment by rdollet** [comment]
For me the solution was to roll back to Node 4.2.6. I'm running Armbian on Orange Pi. Hope this helps.

**Comment by shokk** [comment]
If I do not yet have any plugs as they are on order from Amazon and I'm just playing with homebridge now in advance before they arrive.  Homebridge seems to crash with just the homebridge-hs100 module added, but doesn't when I only have the lightify module (I don't have those yet either).

> TypeError: Cannot read property 'plugs' of null
>     at new Hs100Platform (/usr/local/lib/node_modules/homebridge-hs100/index.js:
> 20:24)
>     at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/
> server.js:312:30)
>     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:79:8)
>     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge
> :17:22)
>     at Module._compile (module.js:573:32)
>     at Object.Module._extensions..js (module.js:582:10)
>     at Module.load (module.js:490:32)
>     at tryModuleLoad (module.js:449:12)
>     at Function.Module._load (module.js:441:3)
> 

I already have config.json in place with the recommended platform entry and a sample WeMo entry. Does the auto discover know to ignore the hs100 platform if no plugs are found or should I just keep homebridge-hs100 uninstalled until the plugs arrive? Is there something I'm missing that isn't letting auto discover run?

> # npm -v
> 4.0.3
> # node -v
> v7.0.0
> # cat /etc/system-release
> CentOS release 6.8 (Final)

**Comment by jpitters3** [comment]
@plasticrake I'm getting the same issue. Everything was working fine using my iPhone on iOS 11.0, but when I updated my iPad to iOS 9.3.5, installed the Ezzi Home app, and gave the app access to HomeKit, now my hs100 is not discovered as an accessory via homebridge (0 accessories and 1 platform). Any ideas what the issue could be?
