### ISSUE TITLE
Plug name not updating

### ISSUE THREAD

**Issue by jaytay79** [plasticrake/homebridge-hs100#8]
I recently got an HS100 and set it up using the name of "Lamp". This showed up in Home fine. I have since updated the name in the Kasa app but Home still shows the old name. I can see the updated name showing in Homebridge OK though:

[12/6/2016, 10:07:15 PM] Online: Charger [80062F50321B8FF2F0F16C599BF93CCE1803281E]

**Comment by leematt** [comment]
I had the same problem. I found the old name cached in .homebridge/accessories/cachedAccessories as the "DisplayName" for one of the services of the HS100, but manually updating that didn't work (and might be irrelevant; I don't know much about the inner workings of Homebridge). So I'm assuming the prior device name is cached in the Home app itself. If you view the details of the device in Home, you can edit its name there.

**Comment by plasticrake** [comment]
The documentation and examples for homebridge are really sparse on how to handle this. Another thing to try is deleting the .homebridge/accessories and .homebridge/persist and removing and re-adding homebridge to your Home.

**Comment by plasticrake** [comment]
From the Homebridge docs:

> Once an accessory has been added to the Home app, changing its name via Homebridge won't be automatically reflected in iOS. You must change it via the Home app as well.
